arachnys/athenapdf

.travis.yml, weaver/Dockerfile
A small change to test if Travis runs the build (and Docker push) for PRs.
=> Add MAINTAINER to Dockerfile

.travis.yml, README.md
@MrSaints please merge if you're happy
=> Small changes to readme

cli/src/athenapdf.js
Test URL: `HTtp://www.google.com`
=> Fix URLs not being detected, and switching to file protocol

cli/package.json, cli/src/athenapdf.js
- Version bump 2.1.2
- Update `did-fail-load` to check if the main frame failed to load
(rather than the conversion URL)
=> Upgrade to Electron v0.37.6

cli/src/athenapdf.js
Added CLI arg to support loading remote URL via proxy. resolves #5
=> Proxy Support

cli/Dockerfile
Fixes missing fonts for google.ae https://s3-eu-west-1.amazonaws.com/athena-pdf-public/846b9f24-c345-4207-8885-66e9a82375f4.pdf
and all missing fonts for google.co.in https://s3-eu-west-1.amazonaws.com/athena-pdf-public/807cf4fc-bd2f-4b3b-b814-3503976495d2.pdf
=> Support for Arabic and various Indian languages

cli/src/athenapdf.js
The rationale behind this is that we will never be able to 'run'
a PDF conversion in this scenario (i.e. when a download dialog
popup shows up). We are better off failing / exiting quickly.
This scenario should not occur in most cases. If it does, the
user should download the file for local conversion (e.g. via
file or stdin).
Additionally, `octet-stream` files are handled well when used
with Weaver.
=> Suppress download popup window / menu

cli/Dockerfile, cli/package.json, cli/src/athenapdf.js
Update to Chrome 51: improved web rendering
=> Upgrade to Electron 1.2.0

README.md
=> Add Core Infrastructure Initiative (CII) badge

cli/package.json, cli/src/athenapdf.js
Several security, and bug fixes.
Refer to Electron upstream for more information:
https://github.com/electron/electron/releases/tag/v1.2.5
=> Upgrade to Electron 1.2.5

cli/package.json, cli/src/athenapdf.js
Refer to https://github.com/electron/electron/releases/tag/v1.3.0 for more information.
Signed-off-by: Ian Lai <ian@fyianlai.com>
=> Upgrade to Electron 1.3.0

cli/Dockerfile
Test page: https://en.wikipedia.org/wiki/Belarusian_language
=> Add DejaVu font package to improve support for Cyrillic scripts

cli/package.json, cli/src/athenapdf.js
- Chrome 53
- Node 6.5.0
See https://github.com/electron/electron/releases/tag/v1.4.0.
=> Upgrade to Electron 1.4.0

cli/Dockerfile, weaver/Dockerfile.build
Update Debian to 8.7 and Go to 1.7.
=> Update Debian and Go version on Dockerfiles

cli/package.json, cli/src/athenapdf.js
- Chrome 56
- Node 7.4.0
See https://github.com/electron/electron/releases/tag/v1.6.1.
Closes #92
=> Upgrade to Electron 1.6.1

README.md, cli/docs/quick-start.md
Notices added to both the readme and quick start. I tried to follow the conventions of those respective documents, and added more detail of the issue to the quick start. Please let me know if you would like for this to be worded differently or want anything else in the commit changed.
Love the etymology of the project!
=> Add volume notice for Windows usage (#102)

Makefile, cli/package.json, cli/src/athenapdf.js, weaver/middleware_test.go
Bump version to v2.10.0.
See: https://github.com/electron/electron/releases/tag/v1.7.5
=> Upgrade Electron to v1.7.5

cli/package.json
=> Update electron version to 3.0.5

cli/src/athenapdf.js, cli/src/plugin_window-status.js, weaver/converter/athenapdf/athenapdf.go, weaver/converter/athenapdf/athenapdf_test.go, weaver/handlers.go
Hi,
I've backported the wait-for-status plugin from the v3 branch to v2 (because I couldn't get the v3 server to work on my setup).
Happy for your feedback & comments!
Best,
Nicolas
=> [Backport] Wait for status before rendering

cli/src/athenapdf.js
For the system to react on errors on electron 3. 
s. https://github.com/electron/electron/issues/12597
=> 'did-get-response-details' no longer functional
