cli/Dockerfile
"If you don't know which mirror to use or your system moves around a lot, you can use the mirror redirector service in your apt sources.list. It dynamically redirects package download requests to the best mirror available based on a number of factors such as mirror availability, location, architecture and freshness. "
From http://debian.org/mirror/list
=> Use httpredir instead of hardcoded ac.uk mirror

cli/src/athenapdf.js
This commit uses the `write` stream callback
to wait until the stream is drained before
exiting.
---
Related to: a03308ddf44740f5bf14ff1965b2754d0feed259 and https://github.com/arachnys/athenapdf/commit/a4c2c465e22c5c7f58429afc9dcf1a4d876aa159.
I haven't merged this yet because I'm running some tests locally.
**Test URLs:**
- https://whispersystems.org/blog/whatsapp-complete/
- http://blog.invisionapp.com/inside-design-wework/
- https://askwonder.com/q/what-big-things-happened-to-time-warner-in-1q2016-part-ii-5706931886302e340038609d
=> Fix app not exiting when data is unbuffered

.travis.yml, Makefile
This commit adds a new `make` subcommand to run an "E2E" test
for the CLI image.
~~~It also adds the ability for Travis to automatically tag, and
push Docker images if it is tagged on Git.~~~
=> Move test commands to Makefile, and add auto-tagging

weaver/Dockerfile
The current structure of the Dockerfile means that anyone pulling this image still has to download the dumb-init package file, rather than just the post-install layer diff. This change flattens those 3 layers into 1.
=> Remove redundant layers in docker image

weaver/converter/athenapdf/athenapdf.go, weaver/converter/athenapdf/athenapdf_test.go, weaver/converter/cloudconvert/cloudconvert.go, weaver/handlers.go
Both converters 'clean up' the temporary file after the
convert method returns. This results in the fallback
converter failing because the file no longer exists.
---
cc: @arachnys/qa 
I don't think this needs much QA. We just need to get it out quick once the tests passes.
=> Fix a bug where a local conversion fails on a fallback due to GC

cli/Dockerfile, cli/src/athenapdf.js
This should:
- Shrink the Docker image size (because we're removing `ttf-mscorefonts-installer`)
- Switch to Liberation font family for Linux (most distros supports it by default)
- Add support for Ethiopian (addresses https://github.com/arachnys/athenapdf/pull/22#issuecomment-215180452)
Oh, and we're installing `wget` because for some reason it is no longer available.
cc: @arachnys/qa
=> Add support for Ethiopian font, and use Liberation font family on Linux

cli/Dockerfile
Hebrew characters were being printed as boxes.
See https://s3-eu-west-1.amazonaws.com/athena-pdf-public/01985f77-0a15-4ff1-a5b6-3ab12c2b46f7.pdf
=> Support for Hebrew characters

cli/README.md, cli/src/athenapdf.js
Currently, the athena CLI does not support the BrowserWindow web preference for scale. This forced canvas elements to render fairly pixelated. This PR allows the passing in of a zoom option to set the zoom scale (e.g. 2 = 200%, 3 = 300%).
Here is a screenshot of a PDF rendered at zoom scale 1:
And here is a screenshot at zoom scale 3:
=> Add support for browser zoom

cli/Dockerfile.build, cli/package.json, cli/src/athenapdf.js
This commit brings athenapdf CLI to v2.3.0.
- Use `process.defaultApp` to process the command line arguments:
`process.argv` is different in a built Electron app vs. a default
app; this change allows us to remove the hack in the Docker build
image
- Notable Electron changes: Chrome 50.0.2661.102, and Node.js 6.1.0
=> Upgrade to Electron 1.1.0

cli/README.md, cli/src/athenapdf.js
The `marginsType` option (from [Electron's printToPDF spec](http://electron.atom.io/docs/api/web-contents/#webcontentsprinttopdfoptions-callback)) was strangely missing, so I added it in now as a CLI argument with the following options:
- standard (0)
- none (1)
- minimal (2)
=> Added support for custom margins

cli/src/plugin_media.js
Some websites define a `media` type for their CSS links.
However, there are times when this is counterintuitive as it makes
the printed version of the page look bad. This hack attempts to
solve the problem by removing the media attribute; it makes 'most'
websites look a lot better.
It currently works by searching for 'text/css' in the link type.
However, this attribute is optional, and defaults to 'text/css',
so quite a few sites do not define this.
This fix looks for `rel=stylesheet` instead as this is an attribute
that MUST be set.
=> Fix minor bug in `screen` media hack

weaver/converter/source.go, weaver/converter/source_test.go, weaver/handlers.go
Previously, local conversions (i.e. save, and load a conversion
file through `/tmp`) are 'extensionless'.
This works fine for majority of use-cases (HTML to PDF).
However, Chromium provides support for loading MHTML files
(message/rfc822) as long as the extension of the file ends with
`.mhtml`, otherwise it will attempt to download the file or
otherwise load it without the necessary formatting.
This commit allows custom file extensions to be specified using
the `ext` parameter (e.g. `?ext=mhtml`).
Alternatively, we could infer the type of the file through a type
hint provided by the request or from the contents of the file.
But, this will add MHTML specific logic that will pollute the
source code, and deviate the project from its original goal of
converting HTML to PDF. The solution …
=> Add support for custom file extensions in a local conversion strategy

cli/src/athenapdf.js
This PR adds some rudimentary error handling when converting a URL into a PDF. If the URL returns HTTP code >= 400, it is now considered an error.
The CLI version will exit with status 1 in this case, and the microservice will return 500 Internal server error.
=> Returning failure on 4XX and 5XX HTTP response codes

cli/package.json, cli/src/athenapdf.js
The current version of `athenapdf` CLI has been tagged `2.4.0` on Docker Hub. If this release proves problematic (which it should not), ensure you are locked-in on version `2.4.0`.
---
Notable changes includes:
- Update to Chrome 51.0.2704.84 (security patches)
- Fix for `executeJavaScript` when used with `webSecurity: false`:
this should resolve problems with plugins not being executed
More information: https://github.com/electron/electron/releases/tag/v1.2.3
=> Upgrade to Electron 1.2.3

cli/Dockerfile, cli/Dockerfile.build, weaver/Dockerfile, weaver/Dockerfile.build
Also, upgraded the Node version used for building the CLI.
---
This will probably cause all sorts of cache invalidation. Also, we should probably be using a fixed version (`FROM arachnysdocker/athenapdf`).
=> Update Dockerfile to remove redundant layers

weaver/config.go, weaver/main.go
This adds TLS server support, as well as providing a way to change the HTTP port.
I can change to using Go's flag library if that's preferred, but at the moment I noticed all configuration is done via environment variables.
=> Added TLS server support

cli/src/athenapdf.js, cli/src/plugin_media.js
The `media` attribute is automatically removed for stylesheet
links if there are no print styles defined.
Previously however, the aforementioned 'autoremoving' behaviour
only applied to elements with `rel=stylesheet`, and it did not
apply to `style` elements.
This commit addresses the problem by including `style` elements
in the query selector.
---
Fixes #61 (Github)
Signed-off-by: Ian Lai <ian@fyianlai.com>
=> Fix `media` plugin / hack for style elements

cli/Dockerfile, cli/fonts.conf
The font configuration is taken directly from:
https://wiki.debian.org/Fonts#Subpixel-hinting_and_Font-smoothing
---
Closes #69
Credits to @rxng for identifying the problem, with a solution.
=> Improve font subpixel hinting, and smoothing

cli/bin/athenapdf, cli/package.json
fixes npm complaining about the following issue. same electron version has been preserved.
`npm WARN deprecated electron-prebuilt@1.4.0: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron`
=> fixes dependency hence electron-prebuilt has been renamed to electron

cli/src/athenapdf.js
This makes sites with WebGL canvases render correctly inside docker (my machine has docker for mac). 
This PR also allows you to produce a pdf of `chrome://gpu` (which helps debug WebGL). 
The ignore-gpu-blacklist line might want to be set conditionally either with a flag? Or if we can detect we're inside Docker?
=> WebGL support inside Docker

cli/src/athenapdf.js
cURL style header implementation
`<command> -H header_key:header_value -H header_key_1:header_value ...`
or
`<command> --http-header key:value --http-header key:value ...`
----
A Different approach to PR #72   - coded before realizing it existed.
=> Add option for Custom Request Headers

weaver/converter/upload_conversion.go, weaver/handlers.go
- made upload conversion processing use chain credentials if static credentials are not provided
- allow caller to pass s3_acl instead of always using public-read acl
=> upload conversion support for aws s3 chain credentials and custom s3 acl

weaver/converter/cloudconvert/cloudconvert.go, weaver/converter/cloudconvert/cloudconvert_test.go, weaver/handlers.go
`5` is an arbitrary number to reduce the likelihood of overlap.
It does not seem like the underlying job is cancelled when the
request is closed. Furthermore, the default timeout for pro
accounts is very high (5 hours). It is better if we timeout quickly
for documents that are large, and likely to fail.
=> Add timeout to CloudConvert job based on the worker timeout

weaver/conf/entrypoint.sh
this solves issues with some Kubernetes environments where /etc/hosts is write protected
=> check if /etc/hosts is writeable before adding bad hosts
